apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://timescaledb-service:5432/telemetrydb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SERVER_PORT: "8081"