apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api-deployment
  labels:
    app: telemetry-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
    spec:
      containers:
        - name: telemetry-api
          image: telemetry-api:v1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: telemetry-config
            - secretRef:
                name: telemetry-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10