apiVersion: v1
kind: Service
metadata:
  name: ai-insights-service
  namespace: telemetry-platform
spec:
  selector:
    app: ai-insights
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
