apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: telemetrypipelines.platform.example.com
spec:
  group: platform.example.com
  scope: Namespaced
  names:
    plural: telemetrypipelines
    singular: telemetrypipeline
    kind: TelemetryPipeline
    shortNames:
      - tp
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                machineID:
                  type: string
                enableAI:
                  type: boolean
                interval:
                  type: integer
            status:
              type: object
              properties:
                phase:
                  type: string
